# Generated by Django 5.2.16 on 2026-07-12 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrecord",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalrecord",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingresa un número de teléfono válido (7 a 15 dígitos).",
                        regex="^\\+?[\\d\\s\\-()]{7,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingresa un número de teléfono válido (7 a 15 dígitos).",
                        regex="^\\+?[\\d\\s\\-()]{7,15}$",
                    )
                ],
            ),
        ),
    ]
