# Generated by Django 5.2.16 on 2026-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_historicalrecord_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecord",
            name="image",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="customer_images/"
            ),
        ),
    ]
