# Generated by Django 5.2.16 on 2026-07-12 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_historicalrecord_image_record_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrecord",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalrecord",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalrecord",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalrecord",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingresa un número de teléfono válido (7 a 15 dígitos).",
                        regex="^\\+?[\\d\\s\\-()]{7,19}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="record",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="record",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingresa un número de teléfono válido (7 a 15 dígitos).",
                        regex="^\\+?[\\d\\s\\-()]{7,19}$",
                    )
                ],
            ),
        ),
    ]
