# Generated by Django 5.1.5 on 2025-02-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_remove_event_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
